version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  api:
    container_name: api
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - api
